<a href="https://colab.research.google.com/github/mesogin/TIS2/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4_%EC%9E%90%EB%A3%8C%ED%98%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#넘파이 자료형
넘파이 자료형은 배열 자료형인 **ndarray**입니다. 넘파이는 수치 해석용 파이썬 패키지이며, 다차원의 배열구조 클래스인  
 **ndarray**클래스를 지원하며 백터와 행렬을 사용하는 선형대수 계산에 주로 사용  
 넘파이는 **판다스(pandas0, 맷플롯립(matplotlib), 텐서플로우(TensorFlow)라이토치(pytorch)**와 같은 딥러닝 패키지의 기초가 되는 패키지이다.

In [ ]:
l = [1, 2, 3, 4]
print(l)

l2 = [1, "A", [1, 2, 3]]
print(l2)

##리스트와 ndarray의 차이점
구분 | 리스트 | ndarray
:--:|:--:|:--:|
요소의 자료형 | 상관없음 | 모두 같은 자료형만 가능
중첩배열구조 | 상관없음 | 요소 배열의 크기가 모두 같아야함
배열 간 연산지원 | 연결만 지원 | 사칙연산 등을 지원
인덱싱 | 하나의 요소만 접근 가능 | 여러 요소 동시 접근 가능

In [13]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])   #int 자료형 포함
arr2 = np.array([1, 2, 3.0, 4]) #float 자료형 포함
arr3 = np.array([1, 2, "3", 4]) #str 자료형 포함

print(type(arr1))
print(type(arr2))
print(type(arr3))

print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1 2 3 4] int64
[1. 2. 3. 4.] float64
['1' '2' '3' '4'] <U21


In [ ]:
#1차원
arr1 = np.array([1, 2, 3])
#print(arr1)

#2차원
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
#print(arr2)

#3차원
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)

In [21]:
#문제 1
#크기가 (4,)인 1차원 넘파이 배열을 생성하시고, 차원 및 형태를 출력해 보세요
#힌트: np.array() 함수 사용, dtype은 명시안함

a= [100, 200, 300, 400]
arr1 = np.array(a)
print('차원', arr1.ndim)  #차원출력
print('형태', arr1.shape)  #형태출력

차원 1
형태 (4,)


In [ ]:
#문제 2
#크기가 (4,3)인 2차원 넘파이 배열을 생성하고 차원 및 형태를 출력해 보세요
b = [[100, 200, 300], [400, 500, 600], [700, 800, 900], [1000, 1100, 1200]]
arr2 = np.array(b)
print('차원', arr2.ndim)
print('형태', arr2.shape)

###arange()함수와 linspace()함수
arange와 linspace함수는 연속으로 요소로 구성된 ndarray를 생성한다.  
arange는 range와 유사하게 (시작점, 끝점, 증가폭)입력하며, linspace는 (시작점, 끝점, 요소개수)를 입력한다.

In [26]:
#0부터 1씩 5번 증가
arr1 = np.arange(5)
display(arr1)

array([0, 1, 2, 3, 4])

In [27]:
#-1 부터 4.5까지 1.5씩증가
arr2 = np.arange(-1, 4.5, 1.5)
display(arr2)

array([-1. ,  0.5,  2. ,  3.5])

In [30]:
#10에서 1까지 2씩 빼면서 만들기
arr3 = np.arange(10, 1, -2)
display(arr3)

array([10,  8,  6,  4,  2])

In [36]:
#0부터 1사이에 요소개수를 11개로 만들어라
arr4 = np.linspace(0, 1, 11)
display(arr4)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

from IPython.core.prefilter import PythonOpsChecker
###zeros 함수
zeros 함수는 0으로만 구성된 배열을 생성하는데 사용
```Python
np.zeros(shape, dtype)
```

In [38]:
z1 = np.zeros(5)
z1

array([0., 0., 0., 0., 0.])

In [40]:
#3차원
z3 = np.zeros((3, 2, 4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [42]:
#모든 값이 false의 숫자값인 0으로 설정이 되어 전부다 false로 처리
arr3 = np.zeros((2, 2), dtype=bool)
arr3

array([[False, False],
       [False, False]])

In [44]:
arr4 = np.ones((5, 2), dtype="i")
arr4

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

###zeros_like , ones_like
다른 배열의 크기와 같은 값으로 만들때 사용하는 함수다.
```python
b = np.zeros((2, 3))

f = np.ones_like(b, dtype="f")
f
```

In [47]:
#ones_like 예시
b = np.zeros((2, 3))
print(b)

f = np.ones_like(b, dtype="f")
print(f)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [50]:
# 연습문제
# 1. 다음 배열(arr1)과 같은 크기를 같으며, 각각 0과 1로만 채워진 두 개의 배열을 생성해 보세요.
arr1 = np.array([[1,2,3], [4,5,6]])

o = np.ones_like(arr1)
z = np.zeros_like(arr1)

print(o)
print(z)

[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


In [51]:
#연습문제 1
#5 크기의 전부 0과 전부 1으로 채워진 넘파이 배열을 생성하시오
z1 = np.zeros(5)
o1 = np.ones(5)
print(z1)
print(o1)

array([0., 0., 0., 0., 0.])

In [61]:
#연습문제 2
#(3,4) 크기의 모두0과 전부 1로 채워진 넘파이 배열을 생성하고 차원과 크기를 출력해 보세요.
z2 = np.zeros((3,4))
o2 = np.ones((3,4))
print(z2, z2.shape, z2.ndim)
print(o2, o2.shape, o2.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4) 2
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4) 2


In [63]:
#연습문제3
# 2. 다음 배열(arr2)과 같은 크기를 같으며, 각각 0과 1로만 채워진 두 개의 배열을 생성해 보세요.  
arr2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

z3 = np.zeros_like(arr2)
o3 = np.ones_like(arr2)

print(arr2)
print(z3)
print(o3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


###random 모듈
**random** 모듈은 넘파이 패키지에 속한 모듈로 다양한 종류의 난수를 생성하는데 사용
```python
np.random.random(shape)
```

In [64]:
arr1 = np.random.random(5)
arr2 = np.random.random((2,2))

print(arr1)
print(arr2)

[0.41637072 0.06965495 0.13835605 0.97941536 0.75798905]
[[0.31895433 0.70102368]
 [0.47595415 0.3157912 ]]


###normal 함수
normal 함수는 정규분포를 따르는 샘플로 구성된 배열을 생성하는데 사용
```python
np.random.normal(loc, scale, size)
```
**loc**는 평균, **scale**은 표준편차, **size**는 배열의 모양


In [66]:
#문제1
#요소개수가 7개이고, 평균이0, 분산이 1인 난수 넘파이 배열 생성하기
x = np.random.normal(0,1,7)
print(x)

[ 0.56702774  0.44206589 -0.39861097  0.45520138 -0.20619796 -0.39993452
  0.81579589]


In [72]:
#문제2
#다음 배열(arr)과 같은 크기의 평균3, 분산이 2인 난수 넘파이 배열생성하기
arr = np.zeros((3,2))
#y = np.random.normal(3, 2, (np.zeros_like(arr)) 크기만 가져와야하는데 잘못가져옴
y = np.random.normal(3, 2, (arr.shape))
display(y)

array([[0.2657946 , 1.08188258],
       [1.9180891 , 1.15712768],
       [2.75545222, 5.31206947]])

In [74]:
#난수의 시드(seed) 설정
np.random.seed(0)

#0과 1사이의 5개의 요소로 구성된 배열생성
#rand() 함수 사용
#시드0번에 저장되어있는 난수 값 표시
np.random.rand(6)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411])

numpy.random.choice(a, size=None, replace=True, p=None)
- a: 배열이면 원래의 데이터, 정수이면 arange 명령으로 데이터생성  
- size: 정수, 샘플숫자  
- replace: 불리언, True이면 한번 선택한 데이터 다시선택 가능  
- p: 배열 합이 1이 나와야함

In [77]:
#오늘 뭐먹지? 라는 모바일 앱을 만드려고 해요
menu = ['라면', '스파게티', '된장찌개', '파전']

menu_arr = np.array(menu)
today_recommended_menu = np.random.choice(menu_arr, 1, replace=True, p=[0.1, 0.1, 0.1, 0.7])
today_recommended_menu

array(['파전'], dtype='<U4')

In [78]:
np.random.randint(10, size=10)

array([6, 8, 8, 1, 6, 7, 7, 8, 1, 5])

In [80]:
#randint: 균일 분포의 정수 난수
# 로또 번호 생성기 (1~45 숫자중에 7개)
np.random.randint(1, 45, size = 7)

array([16,  1, 19, 36, 25, 30, 20])

###배열구조 변경: reshape 메서드
reshape메서드를 아래의 코드로 보면 
배열 arr의 모양을 newshape로 바꾸는데 사용합니다.  
- -1을 입력하면 기존의 열 개수에 맞게 알아서 채워지는 형태
```python
arr.reshape(newshape)
```

In [96]:
#reshape 연습
arr1 = np.zeros((4,3))

arr2 = arr1.reshape(6,2)
print(arr2)
print('_'*30)

arr3 = arr2.reshape(3,4)
print(arr3)
print('_'*30)

#-1을 사용하여 자동으로 설정하는법
arr4 = arr3.reshape(-1, 4) #총 12개의 개수를 행은 자동으로 맞추게 -1설정, 열은 4로 설정
print(arr4)
print('_'*30)


#3차원
arr5 = arr4.reshape(2,3,2)
print(arr5)
print('_'*30)





[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
______________________________
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
______________________________
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
______________________________
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
______________________________


In [102]:
#연습문제
#1. 다음 배열이 주어졌을 때, 이 배열과 구성요소가 같고 크기만 (3,8)로 다른 2차원 배열을 생성하시오.
arr = np.arange(24)
arr1 = arr.reshape(3,8)
print(arr1)

print("")
print("="*30)
print("")

#2. 위 배열을 (6,4) 크기의 배열로 만들되, reshape() 메서드에서 -1을 첫 인자로 활용하세요.
arr2 = arr1.reshape(-1, 4)
print(arr2)

print("")
print("="*30)
print("")

#3. 위 배열을 (3,4,2) 크기의 배열로 만들되, reshape() 메서드에서 -1을 두번째 인자로 활용하세요.
#그리고 원하는 형태로 잘 변형 되었는지 확인해보세요(shape 속성 활용)
arr3 = arr2.reshape(3, -1, 2)
print(arr3, arr3.shape)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]] (3, 4, 2)
