<a href="https://colab.research.google.com/github/mesogin/TIS2/blob/main/%EC%9C%A0%EB%8B%88%EB%B2%84%EC%85%9C_%ED%95%A8%EC%88%98%EC%99%80_%EB%B8%8C%EB%A1%9C%EB%93%9C%EC%BA%90%EC%8A%A4%ED%8C%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#유니버설 함수
**유니버설 함수(universal function)**는 벡터 및 행렬 간 연산을 수행하는 함수입니다. 반복문보다 배열간 연산을 훨씬 빠르고 쉽게 구현 할 수 있다는 장점이 있다.

In [ ]:
#유니버설 함수를 통한 계산
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b


array([5, 7, 9])

###배열 산술 연산
유니버설 함수는 파이썬의 기본 산술 연산자를 사용하기 때문에 특별히 함수명 기억할 필요 X

In [ ]:
x = np.arange(4)
y = np.linspace(1, 10, 4)

print(x)
print(y)
print("x     =", x)
print("y     =", y)
print("x + 5 =", x + 5)
print("x + y =", x + y)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x * y =", x * y)
print("x / 2 =", x / 2)
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

[0 1 2 3]
[ 1.  4.  7. 10.]
x     = [0 1 2 3]
y     = [ 1.  4.  7. 10.]
x + 5 = [5 6 7 8]
x + y = [ 1.  5.  9. 13.]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x * y = [ 0.  4. 14. 30.]
x / 2 = [0.  0.5 1.  1.5]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [ ]:
#연습문제
#1~100까지 원소 (1씩 증가)로 구성된 넘파이 배열이 있다.
x = np.arange(1, 101)
#1. 각각의 요소에 3제곰한 새로운 배열을 생성하시오.
x1 = x ** 3

#2. 각각의 요소를 제곱근을 취한 새로운 배열을 생성하시오.
x2 = np.sqrt(x)

#3. 각각의 요소에 10을 더한 새로운 배열을 생성하시오.
x3 = x + 10
x3

array([ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
        37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
        50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110])

###절대갑 연산
numpy의 **abs**함수를 이용하면 모든요소의 절대값을 구할 수 있다.

In [ ]:
x = np.array([-2, -1, 0, 1, 2])
print("abs(x) = ", np.abs(x))

abs(x) =  [2 1 0 1 2]


###지수, 로그 연산
넘파이의 **exp, exp2, power, log, log2, log10** 함수 등을 이용하면 지수 혹은 로그를 취할 수 있다.

In [ ]:
x = np.array([1, 2, 3])
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))
print("4^x   =", np.power(4, x))
print("ln(x) =", np.log(x)) 
print("log2(x) =", np.log2(x)) 
print("log10(x) =", np.log10(x))

x     = [1 2 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]
4^x   = [ 4 16 64]
ln(x) = [0.         0.69314718 1.09861229]
log2(x) = [0.        1.        1.5849625]
log10(x) = [0.         0.30103    0.47712125]


In [ ]:
# 연습
# 다음 배열의 각각의 원소에 3을 곱하고 1을 뺀 함수를 구현하여 적용하시오.
arr = np.arange(10)

#함수 정의
def plus_Three_Minus_One(x):
  return (x * 3 - 1)

#함수 호출, 인자로 배열 입력
arr1 = plus_Three_Minus_One(arr)
display(arr1)

array([-1,  2,  5,  8, 11, 14, 17, 20, 23, 26])

###비교연산
유니버설 함수로 배열 간 비교 연산이 가능하다.

In [ ]:
#비교연산
x = np.array([1,2,3])
y = np.array([1,3,-2])

print("x == y: ", x == y)
print("x > y:", x > y)
print("x>=1:", x>=1)

#true인 개수 찾기
print(sum(x >= 2))

x == y:  [ True False False]
x > y: [False False  True]
x>=1: [ True  True  True]
2


In [ ]:
#연습문제
#다음 배열에서 짝수인 요소의 개수를 출력하는 코드를 작성하시오.
arr = np.arange(45, dtype = int)
print('짧은버전', sum(arr % 2 == 0))

#긴버전
cond = arr % 2 == 0
print(sum(cond))

#if 버전 (실패)
hap = 0
if (arr % 2 == 0):
  hap += 1
else:
  hap += 0
print(f"if버전{hap}")

짧은버전 23
23
if버전0


###브로드캐스팅


In [ ]:
a = np.array([[1, 2], [3, 4]])  #shape : (2, 2)의 2차원 배열, 즉 행렬
b = np.array([-1, -2]) #shape : (1, )의 1차원 배열, 백터

print(a)
print("="*15)

print(b)
print("="*15)

print(a + b)

[[1 2]
 [3 4]]
[-1 -2]
[[0 0]
 [2 2]]


In [ ]:
import numpy as np
x = np.arange(15).reshape(5, 3)
display(x)  # display 함수를 사용하여 x의 원 구조를 망가트리지 않고 출력

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])