<a href="https://colab.research.google.com/github/mesogin/TIS2/blob/main/%EC%9D%B8%EB%8D%B1%EC%8B%B1%EA%B3%BC_%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#인덱싱과 슬라이싱
1차원의 경우 앞에서부터는 **0, 1, 2** 뒤에서 부터는 **-1 -2 -3** 순서대로 셉니다.  
2차원의 경우 각 차원의 위치에서 요소를 튜플로 접근합니다. 예를들어 **(n,m) n번째 행, m번째 열** 로 접근합니다.

In [3]:
import numpy as np
x = [[1, 2], [3, 4]]
print('리스트 자료형')
print(x)
print(x[1][0])

#ndarray 로 행 변환
arr = np.array(x)
print('넘파이 배열')
print(arr)
print(arr[1,0])


리스트 자료형
[[1, 2], [3, 4]]
3
넘파이 배열
[[1 2]
 [3 4]]
3


###리스트를 이용한 인덱싱과 슬라이싱
ndarray 는 인덱스 리스트를 바탕으로 동시에 둘이상의 요소에 접근 가능하다.  
주의할 점은 X[인덱스] 형태로 인덱싱하므로 괄호를 2개 사용된다는 점이다.

In [4]:
arr = np.arange(1,10)
print(arr[[0,3]])

[1 4]


In [8]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# print('X배열: \n', X)
display('X배열: ', X)
print('='*20)

print(X[0, 1])  # 0행 1열에 있는 값 출력
print(X[[0,1]]) # 0번째 요소, 1번째 요소 출력

#연습문제
#모든행, 2번째열 출력
print(X[:,2])

'X배열: '

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2
[[1 2 3]
 [4 5 6]]
[3 6 9]


In [17]:
#다음 넘파이 배열 대상으로 요구하는 행과 열을 추출하시오
arr = np.arange(30).reshape(5,6)
display(arr)
print("="*30)
#1. 1번째 행 추출
print(f"1번째 행 : {arr[1, :]}")

#2. 0번째 열 추출
print(f"0번째 열 : {arr[:, 0]}")
#3. 1~3번째 행, 0~2번째 열 추출
print(f"1~3번째행, 0~2번째 열 : {arr[1:4, 0:3]}")

#4. 2번째 행, 3~5번째열 추출
print(f"2번째 행, 3~5번째 열 : {arr[2, 3:6]}")

#5. 2~4번째 행, 3번째 열 추출
print(f"2~4번쨰행, 3번째 열 : {arr[2:5, 3]}")

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

1번째 행 : [ 6  7  8  9 10 11]
0번째 열 : [ 0  6 12 18 24]
1~3번째행, 0~2번째 열 : [[ 6  7  8]
 [12 13 14]
 [18 19 20]]
2번째 행, 3~5번째 열 : [15 16 17]
2~4번쨰행, 3번째 열 : [15 21 27]


In [25]:
#연습문제
#오늘의 메뉴를 넘파이 인덱싱 및 슬라이싱 활용하여 추출하기
weekly_lunch = [['백미밥/잡곡밥', '육개장', '두부양념조림', '할라마요함박스테이크', '시금치고추장무침', '콩나물볶음 / 포기김치'], 
                ['백미밥/잡곡밥', '김치수제비', '부대햄야채볶음', '야채계란찜', '수제양념깻잎지', '건파래볶음 / 포기김치'], 
                ['백미밥/잡곡밥','배추된장국','닭볶음탕(김치)','사각어묵야채볶음','브로콜리,물미역&초장','상추겉절이 / 포기김치'], 
                ['백미밥/잡곡밥', '돈육김치찌개', '김치스파게티', '청파래생선까스 & 어니언소스', '느타리유부무침', '미역줄기볶음 / 포기김치'],
                ['백미밥/잡곡밥', '콩나물김치국', '간장불고기', '야채비빔만두', '도토리묵&달래장', '부추겉절이 / 포기김치']]

#넘파이 배열로 변환
weekly_lunch_arr = np.array(weekly_lunch)
# print(weekly_lunch_arr)

# 1. 인덱싱이나 슬라이싱을 활용하여 오늘(수요일)의 메뉴를 출력하시오.
print(f"수요일 메뉴 : {weekly_lunch_arr[2,:]}")

# 2. 인텍싱이나 슬라이싱을 활용하여 오늘(수요일)의 국을 출력하시오.
print(f"수요일 국 : {weekly_lunch_arr[2,1]}")

# 3. 인덱싱이나 슬라이싱을 활용하여 이번 주의 국을 모두 출력하시오.
print(f"이번 주의 국 : {weekly_lunch_arr[:,1]}")

수요일 메뉴 : ['백미밥/잡곡밥' '배추된장국' '닭볶음탕(김치)' '사각어묵야채볶음' '브로콜리,물미역&초장' '상추겉절이 / 포기김치']
수요일 국 : 배추된장국
이번 주의 국 : ['육개장' '김치수제비' '배추된장국' '돈육김치찌개' '콩나물김치국']


In [27]:
#연습문제
#오늘의 메뉴를 넘파이 인덱싱 및 슬라이싱 활용하여 추출하기
weekly_lunch = [['백미밥/잡곡밥', '육개장', '두부양념조림', '할라마요함박스테이크', '시금치고추장무침', '콩나물볶음 / 포기김치'], 
                ['백미밥/잡곡밥', '김치수제비', '부대햄야채볶음', '야채계란찜', '수제양념깻잎지', '건파래볶음 / 포기김치'], 
                ['백미밥/잡곡밥','배추된장국','닭볶음탕(김치)','사각어묵야채볶음','브로콜리,물미역&초장','상추겉절이 / 포기김치'], 
                ['백미밥/잡곡밥', '돈육김치찌개', '김치스파게티', '청파래생선까스 & 어니언소스', '느타리유부무침', '미역줄기볶음 / 포기김치'],
                ['백미밥/잡곡밥', '콩나물김치국', '간장불고기', '야채비빔만두', '도토리묵&달래장', '부추겉절이 / 포기김치']]

#넘파이 배열로 변환
weekly_lunch_arr = np.array(weekly_lunch)
# print(weekly_lunch_arr)

# 1. 인덱싱이나 슬라이싱을 활용하여 오늘(수요일)의 메뉴를 출력하시오.
print(f"수요일 메뉴 : {weekly_lunch_arr[2,:]}")

# 2. 인텍싱이나 슬라이싱을 활용하여 오늘(수요일)의 국을 출력하시오.
print(f"수요일 국 : {weekly_lunch_arr[2,1]}")

# 3. 인덱싱이나 슬라이싱을 활용하여 이번 주의 국을 모두 출력하시오.
print(f"이번 주의 국 : {weekly_lunch_arr[:,1]}")

수요일 메뉴 : ['백미밥/잡곡밥' '배추된장국' '닭볶음탕(김치)' '사각어묵야채볶음' '브로콜리,물미역&초장' '상추겉절이 / 포기김치']
수요일 국 : 배추된장국
이번 주의 국 : ['육개장' '김치수제비' '배추된장국' '돈육김치찌개' '콩나물김치국']


In [28]:
#행과 열 서로 바꿔주는 방법
weekly_lunch_arr_transposed = weekly_lunch_arr.T
print(weekly_lunch_arr_transposed)

[['백미밥/잡곡밥' '백미밥/잡곡밥' '백미밥/잡곡밥' '백미밥/잡곡밥' '백미밥/잡곡밥']
 ['육개장' '김치수제비' '배추된장국' '돈육김치찌개' '콩나물김치국']
 ['두부양념조림' '부대햄야채볶음' '닭볶음탕(김치)' '김치스파게티' '간장불고기']
 ['할라마요함박스테이크' '야채계란찜' '사각어묵야채볶음' '청파래생선까스 & 어니언소스' '야채비빔만두']
 ['시금치고추장무침' '수제양념깻잎지' '브로콜리,물미역&초장' '느타리유부무침' '도토리묵&달래장']
 ['콩나물볶음 / 포기김치' '건파래볶음 / 포기김치' '상추겉절이 / 포기김치' '미역줄기볶음 / 포기김치'
  '부추겉절이 / 포기김치']]


###부울 배열을 활용한 인덱싱과 슬라이싱
부울 배열을 인덱스로 사용이 가능하다. 각요소에 대응하는 인덱스 요소가 True이면 해당요소를 가져올 수 있다.

In [30]:
#부울배열을 활용한 예시
x = np.array([1,2,3,4,5])
b = [True, False, True, True, False]
print(x[b])

[1 3 4]


In [32]:
#필터링을 활용한 예시
x = np.array([1, 2, 3, 4, 5])
cond = x>=3
print(cond)
print(x[cond])

[False False  True  True  True]
[3 4 5]


In [38]:
#연습문제
#1. 다음 배열에서 5보다 작은 요소만 추출하시오.
a = np.arange(10)
cond = a < 5
print(a[cond])

#간단하게
print(f"간단한 버전 : {a[a<5]}")

#2. 위 배열에서 짝수인 요소들만 추출하시오.
#힌트: % 연산자 활용
a = np.arange(10)
cond = a % 2 ==0
print(a[cond])

#간단하게
print(f"간단한 버전 : {a[a % 2 == 0]}")



[0 1 2 3 4]
간단한 버전 : [0 1 2 3 4]
[0 2 4 6 8]
간단한 버전 : [0 2 4 6 8]


In [69]:
#연습문제
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(f"3의 배수 : {x[x%3==0]}")
print(f"4의배수 + 1 : {x[x % 4 == 1]}")
print(f"3의배수, 4의배수+1 의 수 : {x[(x%3==0) & (x%4==1)]}")

3의 배수 : [ 3  6  9 12 15 18]
4의배수 + 1 : [ 1  5  9 13 17]
3의배수, 4의배수+1 의 수 : [9]
