<a href="https://colab.research.google.com/github/mesogin/TIS2/blob/main/%EC%A7%91%EA%B3%84%ED%95%A8%EC%88%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#집계 함수(aggregate function)
배열의 통계량을 구하는데 사용한다.

In [1]:
import numpy as np

x = np.arange(15).reshape(5, 3)

display(x)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

###합계 함수와 axis 인자
행별 합계나 열별 합계를 구하고 싶을 때 axis 인자를 설정합니다. axis는 방향 설정하는 인자로,  
axis=0 행방향(위에서 아래로) axis = 1 열방향 (왼쪽에서 오른쪽) 으로 계산합니다.  
  
axis : 축  
axes : 축 (복수형)  

> [참고그림](https://docs.google.com/presentation/d/1Y7TfqRi7DtSrb4ktR2TeWy8rvTPZD5ECqy7Z_xES_Ys/edit?usp=sharing)

In [7]:
arr = np.arange(15).reshape(5,3)
print(arr)

#행 방향 계산
print("")
print(np.sum(arr, axis=0))
print(arr.sum(axis=0))

#열 방향 계산
print("")
print(np.sum(arr, axis=1))
print(arr.sum(axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

[30 35 40]
[30 35 40]

[ 3 12 21 30 39]
[ 3 12 21 30 39]


# 자주 사용하는 집계 함수

자용 사용하는 집계함수를 다음 표에 정리하였습니다.

함수 | 설명 | 메서드 지원 여부
--|:--:|:--:
sum(x) | x의 합계 | O
min(x) | x의 최솟값 | O
max(x) | x의 최댓값 | O
mean(x) | x의 평균값 | O
std(x) | x의 표준편차 | O
median(x) | x의 중위수(중앙값) | X
quantile(x, q) | x의 상위 q * 100% 값 | X
unique(x) | x에서 중복을 제거한 요소 | X


In [17]:
#다음 리스트를 넘파이 배열로 전환하고, 평균값과 중앙값을 구하시오.
import numpy as np
a_list = [1, 3 ,5, 7, 100]
arr = np.array(a_list)
print("합계",np.sum(arr))
print("최솟값",np.min(arr))
print("최댓값",np.max(arr))
print("평균값",np.mean(arr))
print("표준편차",np.std(arr))
print("중위수 (중앙값)",np.median(arr))
print("상위 q*100%값",np.quantile(arr, 0.2))
print("중복 요소를 제거한 요소",np.unique(arr))


합계 116
최솟값 1
최대값 100
평균값 23.2
표준편차 38.452048059888824
중위수 (중앙값) 5.0
상위 q*100%값 2.6
중복 요소를 제거한 요소 [  1   3   5   7 100]


In [24]:
#연습문제
#다음 배열의 unique() 함수를 적용해 보세요
arr = np.array([1, 3, 5, 7, 9, 3, 5, 100])
print(np.unique(arr))

arr1 = np.unique(arr)
print(arr1)

[  1   3   5   7   9 100]
[  1   3   5   7   9 100]


In [38]:
#연습문제1
#다음과 같은 리스트 자료가 있다. 넘파이 배열로 전환하고, 다음 통계량 들을 구하시오
#평균, 표준편차, 중앙값, 최대값, 최소값
#리스트

a_list = list(range(30))
arr1 = np.array(a_list)
print("배열 : ", arr1)
print("평균 : ",np.mean(arr1))
print("표준편차 : ",np.std(arr1))
print("중앙값 : ",np.median(arr1))
print("최댓값 : ",np.max(arr1))
print("최솟값 : ",np.min(arr1))
print("")
#연습문제2
#위 리스트를 (5, 6) 크기의 넘파이 배열로 전환하고, 열별, 행별 통계량을 구하시오.

arr2 = arr1.reshape(5,6)
print("열별 합", arr2.sum(axis= 0))  #열별 이므로 x1, y1, z1 이런식으로 더해야함(행방향)
print("열별 평균 : ",np.mean(arr2, axis = 0))
print("열별 표준편차 : ",np.std(arr2, axis = 0))
print("열별 중앙값 : ",np.median(arr2, axis = 0))
print("열별 최댓값 : ",np.max(arr2, axis = 0))
print("열별 최솟값 : ",np.min(arr2, axis = 0))
print("")

print("행별 합", arr2.sum(axis= 1))  #행별 이므로 x1, x2, x3 이런식으로 더해야함(열방향)
print("행별 열별", arr2.sum(axis= 1))  #열별 이므로 x1, y1, z1 이런식으로 더해야함(행방향)
print("행별 평균 : ",np.mean(arr2, axis = 1))
print("행별 표준편차 : ",np.std(arr2, axis = 1))
print("행별 중앙값 : ",np.median(arr2, axis = 1))
print("행별 최댓값 : ",np.max(arr2, axis = 1))
print("행별 최솟값 : ",np.min(arr2, axis = 1))

배열 :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
평균 :  14.5
표준편차 :  8.65544144839919
중앙값 :  14.5
최댓값 :  29
최솟값 :  0

열별 합 [60 65 70 75 80 85]
열별 평균 :  [12. 13. 14. 15. 16. 17.]
열별 표준편차 :  [8.48528137 8.48528137 8.48528137 8.48528137 8.48528137 8.48528137]
열별 중앙값 :  [12. 13. 14. 15. 16. 17.]
열별 최댓값 :  [24 25 26 27 28 29]
열별 최솟값 :  [0 1 2 3 4 5]

행별 합 [ 15  51  87 123 159]
행별 열별 [ 15  51  87 123 159]
행별 평균 :  [ 2.5  8.5 14.5 20.5 26.5]
행별 표준편차 :  [1.70782513 1.70782513 1.70782513 1.70782513 1.70782513]
행별 중앙값 :  [ 2.5  8.5 14.5 20.5 26.5]
행별 최댓값 :  [ 5 11 17 23 29]
행별 최솟값 :  [ 0  6 12 18 24]
